# Generated by Django 4.2.6 on 2023-10-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_poost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poost',
            name='content',
            field=models.TextField(max_length=57),
        ),
        migrations.AlterField(
            model_name='poost',
            name='title',
            field=models.CharField(max_length=57),
        ),
    ]
